# Generated by Django 4.0.4 on 2022-06-05 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='contract_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='user',
            name='internal_company_level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='user',
            name='joining_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='marital_status',
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.DateField(max_length=255)),
                ('marital_status', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=255)),
                ('joining_date', models.DateField(default=django.utils.timezone.now)),
                ('department', models.CharField(max_length=255)),
                ('contract_type', models.CharField(max_length=255)),
                ('internal_company_level', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
